branches:
  only: 
    - master
matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "6"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint
    - stage: "Build and Test"
      env: 
        - BuildAndroid="25"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: nvm install stable
      script:
        - cd src && npm i && npm run tsc && cd ../demo
        - travis_wait travis_retry tns build android
    - os: osx
      env: 
        - BuildiOS="10.3"
        - Xcode="8.3"
      osx_image: xcode8.3
      language: node_js 
      node_js: "6"
      jdk: oraclejdk8
      script: 
        - cd src && npm i && npm run tsc && cd ../demo
        - travis_wait travis_retry tns build ios
    - os: linux
      language: android
      env:
        - TestVersion="latest"
      jdk: oraclejdk8
      before_install:
        - nvm install stable
      before_script:
        - cd seed-tests && npm i
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      script: travis_wait travis_retry npm run test.android
      dist: precise
    - os: osx
      env:
        - TestVersion="latest"
      language: node_js
      node_js: "6"
      jdk: oraclejdk8
      osx_image: xcode8.3
      before_script:
        - cd seed-tests && npm i
      script: travis_wait travis_retry npm run test.ios

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

install:
    - npm install -g nativescript
    - npm install -g tslint
    - tns usage-reporting disable
    - tns error-reporting disable
    