branches:
  only:
    - master
matrix:
  include:
    - stage: Lint
      language: node_js
      os: linux
      node_js: "8"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint
    - stage: Build and Test
      env:
        - BuildAndroid="26"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 8
      script:
        - cd src && npm i && npm run tsc && cd ../demo
        - travis_wait travis_retry tns build android
    - os: osx
      env:
        - BuildiOS="11"
        - Xcode="9.2"
      osx_image: xcode9.2
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      script:
        - cd src && npm i && npm run tsc && cd ../demo
        - travis_wait travis_retry tns build ios
    - os: linux
      language: android
      env:
        - TestVersion="latest"
      jdk: oraclejdk8
      before_install:
        - nvm install 8
      before_script:
        - cd seed-tests && npm i
        - >-
          echo no | android create avd --force -n test -t android-21 -b
          armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      script: travis_wait travis_retry npm run test.android
      dist: precise
    - os: osx
      env:
        - TestVersion="latest"
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      osx_image: xcode9.2
      before_script:
        - cd seed-tests && npm i
      script: travis_wait travis_retry npm run test.ios
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-23
    - android-26
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
install:
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable
